services:
  - type: web
    name: cr-rlf-osint
    env: node
    region: frankfurt
    plan: starter
    branch: main
    buildCommand: npm ci && npx prisma migrate deploy && npm run build
    startCommand: npm start
    healthCheckPath: /sign-in
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: cr-rlf-db
          property: connectionString
      - key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: CLERK_WEBHOOK_SIGNING_SECRET
        sync: false
      - key: APP_URL
        sync: false
      - key: NEXT_PUBLIC_CLERK_SIGN_IN_URL
        value: /sign-in
      - key: NEXT_PUBLIC_CLERK_SIGN_UP_URL
        value: /sign-in
      - key: NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL
        value: /dashboard
      - key: NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL
        value: /dashboard

databases:
  - name: cr-rlf-db
    databaseName: cr_rlf
    region: frankfurt
    plan: basic-256mb
